// Catálogo de tecnologías. Primero intenta usar logos originales/multicolor de Devicon
// y si no existe usa Simple Icons con el color oficial de marca.
export type Tech = { slug: string; label: string; color: string; customUrl?: string };

export const TECHS: Tech[] = [
  // Frontend frameworks / meta-frameworks
  { slug: "react", label: "React", color: "61DAFB" },
  { slug: "nextdotjs", label: "Next.js", color: "FFFFFF" },
  { slug: "vuedotjs", label: "Vue", color: "4FC08D" },
  { slug: "nuxt", label: "Nuxt", color: "00DC82" },
  { slug: "angular", label: "Angular", color: "DD0031" },
  { slug: "svelte", label: "Svelte", color: "FF3E00" },
  { slug: "astro", label: "Astro", color: "BC52EE" },
  { slug: "remix", label: "Remix", color: "FFFFFF" },
  { slug: "solid", label: "SolidJS", color: "2C4F7C" },
  { slug: "qwik", label: "Qwik", color: "AC7EF4" },
  { slug: "emberdotjs", label: "Ember", color: "E04E39" },
  { slug: "preact", label: "Preact", color: "673AB8" },
  { slug: "alpinedotjs", label: "Alpine.js", color: "8BC0D0" },
  { slug: "lit", label: "Lit", color: "324FFF" },
  { slug: "stencil", label: "Stencil", color: "4B7BE5" },
  { slug: "htmx", label: "htmx", color: "3366CC" },
  { slug: "tanstack", label: "TanStack", color: "FF4154" },
  { slug: "redux", label: "Redux", color: "764ABC" },
  { slug: "mobx", label: "MobX", color: "FF9955" },
  { slug: "zod", label: "Zod", color: "3E67B1" },
  // Languages
  { slug: "javascript", label: "JavaScript", color: "F7DF1E" },
  { slug: "typescript", label: "TypeScript", color: "3178C6" },
  { slug: "html5", label: "HTML5", color: "E34F26" },
  { slug: "css", label: "CSS3", color: "1572B6" },
  { slug: "python", label: "Python", color: "3776AB" },
  { slug: "java", label: "Java", color: "ED8B00" },
  { slug: "kotlin", label: "Kotlin", color: "7F52FF" },
  { slug: "go", label: "Go", color: "00ADD8" },
  { slug: "rust", label: "Rust", color: "FFFFFF" },
  { slug: "php", label: "PHP", color: "777BB4" },
  { slug: "ruby", label: "Ruby", color: "CC342D" },
  { slug: "csharp", label: "C#", color: "239120" },
  { slug: "cplusplus", label: "C++", color: "00599C" },
  { slug: "c", label: "C", color: "A8B9CC" },
  { slug: "swift", label: "Swift", color: "F05138" },
  { slug: "dart", label: "Dart", color: "0175C2" },
  { slug: "scala", label: "Scala", color: "DC322F" },
  { slug: "elixir", label: "Elixir", color: "4B275F" },
  { slug: "erlang", label: "Erlang", color: "A90533" },
  { slug: "haskell", label: "Haskell", color: "5D4F85" },
  { slug: "clojure", label: "Clojure", color: "5881D8" },
  { slug: "fsharp", label: "F#", color: "378BBA" },
  { slug: "ocaml", label: "OCaml", color: "EC6813" },
  { slug: "lua", label: "Lua", color: "2C2D72" },
  { slug: "r", label: "R", color: "276DC3" },
  { slug: "julia", label: "Julia", color: "9558B2" },
  { slug: "perl", label: "Perl", color: "39457E" },
  { slug: "crystal", label: "Crystal", color: "FFFFFF" },
  { slug: "nim", label: "Nim", color: "FFE953" },
  { slug: "zig", label: "Zig", color: "F7A41D" },
  { slug: "gnubash", label: "Bash", color: "4EAA25" },
  { slug: "shell", label: "Shell", color: "FFFFFF" },
  { slug: "powershell", label: "PowerShell", color: "5391FE" },
  { slug: "gnu", label: "GNU", color: "A42E2B" },
  { slug: "assemblyscript", label: "AssemblyScript", color: "007AAC" },
  { slug: "webassembly", label: "WebAssembly", color: "654FF0" },
  { slug: "solidity", label: "Solidity", color: "363636" },
  { slug: "elm", label: "Elm", color: "1293D8" },
  // CSS / UI
  { slug: "tailwindcss", label: "Tailwind", color: "06B6D4" },
  { slug: "sass", label: "Sass", color: "CC6699" },
  { slug: "less", label: "Less", color: "1D365D" },
  { slug: "bootstrap", label: "Bootstrap", color: "7952B3" },
  { slug: "bulma", label: "Bulma", color: "00D1B2" },
  { slug: "chakraui", label: "Chakra UI", color: "319795" },
  { slug: "mui", label: "Material UI", color: "007FFF" },
  { slug: "radixui", label: "Radix UI", color: "FFFFFF" },
  { slug: "shadcnui", label: "shadcn/ui", color: "FFFFFF" },
  { slug: "styledcomponents", label: "Styled Components", color: "DB7093" },
  { slug: "framer", label: "Framer", color: "0055FF" },
  // Backend
  { slug: "nodedotjs", label: "Node.js", color: "5FA04E" },
  { slug: "bun", label: "Bun", color: "FFFFFF" },
  { slug: "deno", label: "Deno", color: "FFFFFF" },
  { slug: "express", label: "Express", color: "FFFFFF" },
  { slug: "nestjs", label: "NestJS", color: "E0234E" },
  { slug: "fastify", label: "Fastify", color: "FFFFFF" },
  { slug: "hono", label: "Hono", color: "E36002" },
  { slug: "koa", label: "Koa", color: "33333D" },
  { slug: "django", label: "Django", color: "092E20" },
  { slug: "flask", label: "Flask", color: "FFFFFF" },
  { slug: "fastapi", label: "FastAPI", color: "009688" },
  { slug: "spring", label: "Spring", color: "6DB33F" },
  { slug: "springboot", label: "Spring Boot", color: "6DB33F" },
  { slug: "laravel", label: "Laravel", color: "FF2D20" },
  { slug: "symfony", label: "Symfony", color: "FFFFFF" },
  { slug: "rubyonrails", label: "Rails", color: "D30001" },
  { slug: "dotnet", label: ".NET", color: "512BD4" },
  { slug: "flutter", label: "Flutter", color: "02569B" },
  { slug: "reactnative", label: "React Native", color: "61DAFB" },
  { slug: "expo", label: "Expo", color: "FFFFFF" },
  { slug: "ionic", label: "Ionic", color: "3880FF" },
  { slug: "electron", label: "Electron", color: "47848F" },
  { slug: "tauri", label: "Tauri", color: "FFC131" },
  { slug: "tanstack", label: "TanStack Router", color: "FF4154" },
  // Databases
  { slug: "postgresql", label: "PostgreSQL", color: "4169E1" },
  { slug: "mysql", label: "MySQL", color: "4479A1" },
  { slug: "mariadb", label: "MariaDB", color: "003545" },
  { slug: "sqlite", label: "SQLite", color: "003B57" },
  { slug: "mongodb", label: "MongoDB", color: "47A248" },
  { slug: "redis", label: "Redis", color: "FF4438" },
  { slug: "cassandra", label: "Cassandra", color: "1287B1" },
  { slug: "elasticsearch", label: "Elasticsearch", color: "005571" },
  { slug: "neo4j", label: "Neo4j", color: "4581C3" },
  { slug: "apachecouchdb", label: "CouchDB", color: "E42528" },
  { slug: "influxdb", label: "InfluxDB", color: "22ADF6" },
  { slug: "dgraph", label: "Dgraph", color: "E50695" },
  { slug: "duckdb", label: "DuckDB", color: "FFF000" },
  { slug: "snowflake", label: "Snowflake", color: "29B5E8" },
  { slug: "supabase", label: "Supabase", color: "3FCF8E" },
  { slug: "firebase", label: "Firebase", color: "DD2C00" },
  { slug: "planetscale", label: "PlanetScale", color: "FFFFFF" },
  { slug: "prisma", label: "Prisma", color: "FFFFFF" },
  { slug: "drizzle", label: "Drizzle", color: "C5F74F" },
  { slug: "sequelize", label: "Sequelize", color: "52B0E7" },
  { slug: "typeorm", label: "TypeORM", color: "FE0902" },
  { slug: "graphql", label: "GraphQL", color: "E10098" },
  { slug: "apollographql", label: "Apollo", color: "FFFFFF" },
  { slug: "trpc", label: "tRPC", color: "2596BE" },
  // DevOps / Cloud
  { slug: "docker", label: "Docker", color: "2496ED" },
  { slug: "kubernetes", label: "Kubernetes", color: "326CE5" },
  { slug: "podman", label: "Podman", color: "892CA0" },
  { slug: "helm", label: "Helm", color: "0F1689" },
  { slug: "terraform", label: "Terraform", color: "844FBA" },
  { slug: "ansible", label: "Ansible", color: "EE0000" },
  { slug: "pulumi", label: "Pulumi", color: "F7BF2A" },
  { slug: "amazonwebservices", label: "AWS", color: "FF9900" },
  { slug: "oracle", label: "Oracle", color: "F80000" },
  { slug: "googlecloud", label: "GCP", color: "4285F4" },
  { slug: "microsoftazure", label: "Azure", color: "0078D4" },
  { slug: "digitalocean", label: "DigitalOcean", color: "0080FF" },
  { slug: "linode", label: "Linode", color: "00A95C" },
  { slug: "heroku", label: "Heroku", color: "430098" },
  { slug: "vercel", label: "Vercel", color: "FFFFFF" },
  { slug: "netlify", label: "Netlify", color: "00C7B7" },
  { slug: "render", label: "Render", color: "46E3B7" },
  { slug: "railway", label: "Railway", color: "0B0D0E" },
  { slug: "flydotio", label: "Fly.io", color: "FFFFFF" },
  { slug: "cloudflare", label: "Cloudflare", color: "F38020" },
  { slug: "nginx", label: "Nginx", color: "009639" },
  { slug: "apache", label: "Apache", color: "D22128" },
  { slug: "caddy", label: "Caddy", color: "1F88C0" },
  { slug: "traefikproxy", label: "Traefik", color: "24A1C1" },
  { slug: "linux", label: "Linux", color: "FCC624" },
  { slug: "ubuntu", label: "Ubuntu", color: "E95420" },
  { slug: "debian", label: "Debian", color: "A81D33" },
  { slug: "archlinux", label: "Arch Linux", color: "1793D1" },
  { slug: "fedora", label: "Fedora", color: "294172" },
  { slug: "redhat", label: "Red Hat", color: "EE0000" },
  { slug: "alpinelinux", label: "Alpine Linux", color: "0D597F" },
  { slug: "apple", label: "macOS", color: "FFFFFF" },
  { slug: "windows", label: "Windows", color: "0078D4" },
  { slug: "android", label: "Android", color: "34A853" },
  { slug: "ios", label: "iOS", color: "FFFFFF" },
  // CI/CD & VCS
  { slug: "git", label: "Git", color: "F05032" },
  { slug: "github", label: "GitHub", color: "FFFFFF" },
  { slug: "githubactions", label: "GitHub Actions", color: "2088FF" },
  { slug: "gitlab", label: "GitLab", color: "FC6D26" },
  { slug: "bitbucket", label: "Bitbucket", color: "0052CC" },
  { slug: "jenkins", label: "Jenkins", color: "D24939" },
  { slug: "circleci", label: "CircleCI", color: "343434" },
  { slug: "travisci", label: "Travis CI", color: "3EAAAF" },
  { slug: "argo", label: "Argo CD", color: "EF7B4D" },
  // Build tools
  { slug: "vite", label: "Vite", color: "646CFF" },
  { slug: "webpack", label: "Webpack", color: "8DD6F9" },
  { slug: "rollupdotjs", label: "Rollup", color: "EC4A3F" },
  { slug: "esbuild", label: "esbuild", color: "FFCF00" },
  { slug: "turbo", label: "Turbo", color: "EF4444" },
  { slug: "swc", label: "SWC", color: "FFFFFF" },
  { slug: "babel", label: "Babel", color: "F9DC3E" },
  { slug: "pnpm", label: "pnpm", color: "F69220" },
  { slug: "yarn", label: "Yarn", color: "2C8EBB" },
  { slug: "npm", label: "npm", color: "CB3837" },
  // Testing
  { slug: "jest", label: "Jest", color: "C21325" },
  { slug: "vitest", label: "Vitest", color: "6E9F18" },
  { slug: "mocha", label: "Mocha", color: "8D6748" },
  { slug: "cypress", label: "Cypress", color: "69D3A7" },
  { slug: "playwright", label: "Playwright", color: "2EAD33" },
  { slug: "selenium", label: "Selenium", color: "43B02A" },
  { slug: "puppeteer", label: "Puppeteer", color: "40B5A4" },
  { slug: "storybook", label: "Storybook", color: "FF4785" },
  { slug: "testinglibrary", label: "Testing Library", color: "E33332" },
  // Design
  { slug: "figma", label: "Figma", color: "F24E1E" },
  { slug: "adobexd", label: "Adobe XD", color: "FF61F6" },
  { slug: "adobephotoshop", label: "Photoshop", color: "31A8FF" },
  { slug: "adobeillustrator", label: "Illustrator", color: "FF9A00" },
  { slug: "adobepremierepro", label: "Premiere Pro", color: "9999FF" },
  { slug: "adobeaftereffects", label: "After Effects", color: "9999FF" },
  { slug: "sketch", label: "Sketch", color: "F7B500" },
  { slug: "canva", label: "Canva", color: "00C4CC" },
  { slug: "blender", label: "Blender", color: "E87D0D" },
  // AI / Data
  { slug: "openai", label: "OpenAI", color: "FFFFFF" },
  { slug: "anthropic", label: "Anthropic", color: "D4A27F" },
  { slug: "googlegemini", label: "Gemini", color: "8E75B2" },
  { slug: "huggingface", label: "Hugging Face", color: "FFD21E" },
  { slug: "tensorflow", label: "TensorFlow", color: "FF6F00" },
  { slug: "pytorch", label: "PyTorch", color: "EE4C2C" },
  { slug: "keras", label: "Keras", color: "D00000" },
  { slug: "scikitlearn", label: "scikit-learn", color: "F7931E" },
  { slug: "pandas", label: "pandas", color: "150458" },
  { slug: "numpy", label: "NumPy", color: "013243" },
  { slug: "jupyter", label: "Jupyter", color: "F37626" },
  { slug: "langchain", label: "LangChain", color: "1C3C3C" },
  { slug: "ollama", label: "Ollama", color: "FFFFFF" },
  // Messaging / Streams
  { slug: "apachekafka", label: "Kafka", color: "FFFFFF" },
  { slug: "rabbitmq", label: "RabbitMQ", color: "FF6600" },
  { slug: "nats", label: "NATS", color: "27AAE1" },
  // Payments / SaaS APIs
  { slug: "stripe", label: "Stripe", color: "635BFF" },
  { slug: "paypal", label: "PayPal", color: "00457C" },
  { slug: "mercadopago", label: "Mercado Pago", color: "00B1EA" },
  { slug: "twilio", label: "Twilio", color: "F22F46" },
  { slug: "sendgrid", label: "SendGrid", color: "1A82E2" },
  { slug: "resend", label: "Resend", color: "FFFFFF" },
  { slug: "mailchimp", label: "Mailchimp", color: "FFE01B" },
  { slug: "auth0", label: "Auth0", color: "EB5424" },
  { slug: "clerk", label: "Clerk", color: "6C47FF" },
  { slug: "okta", label: "Okta", color: "007DC1" },
  // Tools
  { slug: "postman", label: "Postman", color: "FF6C37" },
  { slug: "insomnia", label: "Insomnia", color: "4000BF" },
  { slug: "swagger", label: "Swagger", color: "85EA2D" },
  { slug: "notion", label: "Notion", color: "FFFFFF" },
  { slug: "obsidian", label: "Obsidian", color: "7C3AED" },
  { slug: "slack", label: "Slack", color: "4A154B" },
  { slug: "discord", label: "Discord", color: "5865F2" },
  { slug: "jira", label: "Jira", color: "0052CC" },
  { slug: "linear", label: "Linear", color: "5E6AD2" },
  { slug: "trello", label: "Trello", color: "0079BF" },
  { slug: "visualstudiocode", label: "VS Code", color: "007ACC" },
  { slug: "neovim", label: "Neovim", color: "57A143" },
  { slug: "vim", label: "Vim", color: "019733" },
  { slug: "jetbrains", label: "JetBrains", color: "FFFFFF" },
  { slug: "intellijidea", label: "IntelliJ IDEA", color: "FFFFFF" },
  { slug: "androidstudio", label: "Android Studio", color: "3DDC84" },
  { slug: "xcode", label: "Xcode", color: "147EFB" },
  { slug: "pycharm", label: "PyCharm", color: "21D789" },
  { slug: "webstorm", label: "WebStorm", color: "00CDD7" },
  { slug: "phpstorm", label: "PhpStorm", color: "B345F1" },
  { slug: "goland", label: "GoLand", color: "0EBFE9" },
  { slug: "rubymine", label: "RubyMine", color: "FE2857" },
  { slug: "rider", label: "Rider", color: "C90F5E" },
  { slug: "clion", label: "CLion", color: "22D88F" },
  { slug: "datagrip", label: "DataGrip", color: "21D789" },
  { slug: "sublimetext", label: "Sublime Text", color: "FF9800" },
  { slug: "atom", label: "Atom", color: "66595C" },
  { slug: "eclipseide", label: "Eclipse", color: "2C2255" },
  { slug: "notepadplusplus", label: "Notepad++", color: "90E59A" },
  { slug: "zedindustries", label: "Zed", color: "084CCF" },
  { slug: "cursor", label: "Cursor", color: "FFFFFF" },
  { slug: "antigravity", label: "Antigravity IDE", color: "00DC82" },
  { slug: "anaconda", label: "Anaconda", color: "44A833" },
  { slug: "pypi", label: "pip / PyPI", color: "3775A9" },
  { slug: "poetry", label: "Poetry", color: "60A5FA" },
  // CMS / Site
  { slug: "wordpress", label: "WordPress", color: "21759B" },
  { slug: "shopify", label: "Shopify", color: "7AB55C" },
  { slug: "strapi", label: "Strapi", color: "4945FF" },
  { slug: "sanity", label: "Sanity", color: "F03E2F" },
  { slug: "contentful", label: "Contentful", color: "2478CC" },
  { slug: "ghost", label: "Ghost", color: "FFFFFF" },
  // Game / 3D
  { slug: "unity", label: "Unity", color: "FFFFFF" },
  { slug: "unrealengine", label: "Unreal Engine", color: "FFFFFF" },
  { slug: "godotengine", label: "Godot", color: "478CBF" },
  { slug: "threedotjs", label: "Three.js", color: "FFFFFF" },
];

const BY_SLUG = new Map(TECHS.map((t) => [t.slug, t]));
const BY_LABEL = new Map(TECHS.map((t) => [t.label.toLowerCase(), t]));
const ALIASES: Record<string, string> = {
  js: "javascript",
  ts: "typescript",
  node: "nodedotjs",
  "node.js": "nodedotjs",
  nodejs: "nodedotjs",
  next: "nextdotjs",
  "next.js": "nextdotjs",
  nextjs: "nextdotjs",
  vue: "vuedotjs",
  postgres: "postgresql",
  mongo: "mongodb",
  tailwind: "tailwindcss",
  aws: "amazonwebservices",
  css3: "css",
  gcp: "googlecloud",
  azure: "microsoftazure",
  "c#": "csharp",
  ".net": "dotnet",
  rails: "rubyonrails",
  "react native": "reactnative",
};

const DEVICON_BASE = "https://cdn.jsdelivr.net/gh/devicons/devicon/icons";

const ORIGINAL_ICON_PATHS: Record<string, string> = {
  react: "react/react-original.svg",
  reactnative: "react/react-original.svg",
  nextdotjs: "nextjs/nextjs-original.svg",
  vuedotjs: "vuejs/vuejs-original.svg",
  nuxt: "nuxtjs/nuxtjs-original.svg",
  angular: "angularjs/angularjs-original.svg",
  svelte: "svelte/svelte-original.svg",
  emberdotjs: "ember/ember-original-wordmark.svg",
  javascript: "javascript/javascript-original.svg",
  typescript: "typescript/typescript-original.svg",
  html5: "html5/html5-original.svg",
  css: "css3/css3-original.svg",
  python: "python/python-original.svg",
  java: "java/java-original.svg",
  kotlin: "kotlin/kotlin-original.svg",
  go: "go/go-original.svg",
  rust: "rust/rust-original.svg",
  php: "php/php-original.svg",
  ruby: "ruby/ruby-original.svg",
  csharp: "csharp/csharp-original.svg",
  cplusplus: "cplusplus/cplusplus-original.svg",
  c: "c/c-original.svg",
  swift: "swift/swift-original.svg",
  dart: "dart/dart-original.svg",
  scala: "scala/scala-original.svg",
  elixir: "elixir/elixir-original.svg",
  erlang: "erlang/erlang-original.svg",
  haskell: "haskell/haskell-original.svg",
  clojure: "clojure/clojure-original.svg",
  fsharp: "fsharp/fsharp-original.svg",
  ocaml: "ocaml/ocaml-original.svg",
  lua: "lua/lua-original.svg",
  r: "r/r-original.svg",
  julia: "julia/julia-original.svg",
  perl: "perl/perl-original.svg",
  nim: "nim/nim-original.svg",
  zig: "zig/zig-original.svg",
  gnubash: "bash/bash-original.svg",
  shell: "bash/bash-original.svg",
  powershell: "powershell/powershell-original.svg",
  webassembly: "wasm/wasm-original.svg",
  tailwindcss: "tailwindcss/tailwindcss-original.svg",
  sass: "sass/sass-original.svg",
  less: "less/less-plain-wordmark.svg",
  bootstrap: "bootstrap/bootstrap-original.svg",
  bulma: "bulma/bulma-plain.svg",
  mui: "materialui/materialui-original.svg",
  nodedotjs: "nodejs/nodejs-original.svg",
  deno: "denojs/denojs-original.svg",
  express: "express/express-original.svg",
  nestjs: "nestjs/nestjs-original.svg",
  django: "django/django-plain.svg",
  flask: "flask/flask-original.svg",
  fastapi: "fastapi/fastapi-original.svg",
  spring: "spring/spring-original.svg",
  springboot: "spring/spring-original.svg",
  laravel: "laravel/laravel-original.svg",
  symfony: "symfony/symfony-original.svg",
  rubyonrails: "rails/rails-original-wordmark.svg",
  dotnet: "dot-net/dot-net-original.svg",
  flutter: "flutter/flutter-original.svg",
  electron: "electron/electron-original.svg",
  postgresql: "postgresql/postgresql-original.svg",
  mysql: "mysql/mysql-original.svg",
  mariadb: "mariadb/mariadb-original.svg",
  sqlite: "sqlite/sqlite-original.svg",
  mongodb: "mongodb/mongodb-original.svg",
  redis: "redis/redis-original.svg",
  cassandra: "cassandra/cassandra-original.svg",
  elasticsearch: "elasticsearch/elasticsearch-original.svg",
  neo4j: "neo4j/neo4j-original.svg",
  apachecouchdb: "couchdb/couchdb-original.svg",
  influxdb: "influxdb/influxdb-original.svg",
  supabase: "supabase/supabase-original.svg",
  firebase: "firebase/firebase-original.svg",
  prisma: "prisma/prisma-original.svg",
  sequelize: "sequelize/sequelize-original.svg",
  graphql: "graphql/graphql-plain.svg",
  docker: "docker/docker-original.svg",
  kubernetes: "kubernetes/kubernetes-original.svg",
  podman: "podman/podman-original.svg",
  terraform: "terraform/terraform-original.svg",
  ansible: "ansible/ansible-original.svg",
  amazonwebservices: "amazonwebservices/amazonwebservices-original-wordmark.svg",
  oracle: "oracle/oracle-original.svg",
  googlecloud: "googlecloud/googlecloud-original.svg",
  microsoftazure: "azure/azure-original.svg",
  digitalocean: "digitalocean/digitalocean-original.svg",
  heroku: "heroku/heroku-original.svg",
  vercel: "vercel/vercel-original.svg",
  cloudflare: "cloudflare/cloudflare-original.svg",
  nginx: "nginx/nginx-original.svg",
  apache: "apache/apache-original.svg",
  linux: "linux/linux-original.svg",
  ubuntu: "ubuntu/ubuntu-original.svg",
  debian: "debian/debian-original.svg",
  windows: "windows11/windows11-original.svg",
  android: "android/android-original.svg",
  apple: "apple/apple-original.svg",
  git: "git/git-original.svg",
  github: "github/github-original.svg",
  gitlab: "gitlab/gitlab-original.svg",
  bitbucket: "bitbucket/bitbucket-original.svg",
  vite: "vitejs/vitejs-original.svg",
  webpack: "webpack/webpack-original.svg",
  babel: "babel/babel-original.svg",
  pnpm: "pnpm/pnpm-original.svg",
  yarn: "yarn/yarn-original.svg",
  npm: "npm/npm-original-wordmark.svg",
  jest: "jest/jest-plain.svg",
  playwright: "playwright/playwright-original.svg",
  selenium: "selenium/selenium-original.svg",
  storybook: "storybook/storybook-original.svg",
  figma: "figma/figma-original.svg",
  adobephotoshop: "photoshop/photoshop-original.svg",
  adobeillustrator: "illustrator/illustrator-plain.svg",
  adobepremierepro: "premierepro/premierepro-original.svg",
  adobeaftereffects: "aftereffects/aftereffects-original.svg",
  blender: "blender/blender-original.svg",
  tensorflow: "tensorflow/tensorflow-original.svg",
  pytorch: "pytorch/pytorch-original.svg",
  keras: "keras/keras-original.svg",
  pandas: "pandas/pandas-original.svg",
  numpy: "numpy/numpy-original.svg",
  jupyter: "jupyter/jupyter-original.svg",
  postman: "postman/postman-original.svg",
  swagger: "swagger/swagger-original.svg",
  visualstudiocode: "vscode/vscode-original.svg",
  neovim: "neovim/neovim-original.svg",
  vim: "vim/vim-original.svg",
  jetbrains: "jetbrains/jetbrains-original.svg",
  intellijidea: "intellij/intellij-original.svg",
  androidstudio: "androidstudio/androidstudio-original.svg",
  xcode: "xcode/xcode-original.svg",
  wordpress: "wordpress/wordpress-original.svg",
  unity: "unity/unity-original.svg",
  godotengine: "godot/godot-original.svg",
  threedotjs: "threejs/threejs-original.svg",
  pycharm: "pycharm/pycharm-original.svg",
  webstorm: "webstorm/webstorm-original.svg",
  phpstorm: "phpstorm/phpstorm-original.svg",
  goland: "goland/goland-original.svg",
  rubymine: "rubymine/rubymine-original.svg",
  rider: "rider/rider-original.svg",
  clion: "clion/clion-original.svg",
  datagrip: "datagrip/datagrip-original.svg",
  anaconda: "anaconda/anaconda-original.svg",
};

export function resolveTech(value: string): Tech | null {
  if (!value) return null;
  const v = value.trim();
  if (BY_SLUG.has(v)) return BY_SLUG.get(v)!;
  const low = v.toLowerCase();
  if (BY_LABEL.has(low)) return BY_LABEL.get(low)!;
  const alias = ALIASES[low];
  if (alias && BY_SLUG.has(alias)) return BY_SLUG.get(alias)!;
  return null;
}

export function techIconUrl(t: Tech): string {
  if (t.customUrl) return t.customUrl;
  const originalPath = ORIGINAL_ICON_PATHS[t.slug];
  if (originalPath) return `${DEVICON_BASE}/${originalPath}`;
  return `https://cdn.simpleicons.org/${t.slug}/${t.color}`;
}

// ====== Auto-categorización ======
export type TechCategory = "frontend" | "backend" | "devops" | "tools" | "design" | "ai";

const CATEGORY_BY_SLUG: Record<string, TechCategory> = {};
const set = (cat: TechCategory, slugs: string[]) => slugs.forEach((s) => (CATEGORY_BY_SLUG[s] = cat));

set("frontend", [
  "react","nextdotjs","vuedotjs","nuxt","angular","svelte","astro","remix","solid","qwik",
  "emberdotjs","preact","alpinedotjs","lit","stencil","htmx","tanstack","redux","mobx","zod",
  "javascript","typescript","html5","css","tailwindcss","sass","less","bootstrap","bulma",
  "chakraui","mui","radixui","shadcnui","styledcomponents","framer",
  "flutter","reactnative","expo","ionic","electron","tauri","ios","android",
]);
set("backend", [
  "nodedotjs","bun","deno","express","nestjs","fastify","hono","koa","django","flask",
  "fastapi","spring","springboot","laravel","symfony","rubyonrails","dotnet",
  "python","java","kotlin","go","rust","php","ruby","csharp","cplusplus","c","swift","dart",
  "scala","elixir","erlang","haskell","clojure","fsharp","ocaml","lua","r","julia","perl",
  "crystal","nim","zig","gnubash","shell","powershell","gnu","assemblyscript","webassembly",
  "solidity","elm","graphql","apollographql","trpc","prisma","drizzle","sequelize","typeorm",
  "postgresql","mysql","mariadb","sqlite","mongodb","redis","cassandra","elasticsearch",
  "neo4j","apachecouchdb","influxdb","dgraph","duckdb","snowflake","supabase","firebase",
  "planetscale","apachekafka","rabbitmq","nats",
]);
set("devops", [
  "docker","kubernetes","podman","helm","terraform","ansible","pulumi","amazonwebservices",
  "oracle","googlecloud","microsoftazure","digitalocean","linode","heroku","vercel","netlify",
  "render","railway","flydotio","cloudflare","nginx","apache","caddy","traefikproxy",
  "linux","ubuntu","debian","archlinux","fedora","redhat","alpinelinux","apple","windows",
  "git","github","githubactions","gitlab","bitbucket","jenkins","circleci","travisci","argo",
]);
set("design", [
  "figma","adobexd","adobephotoshop","adobeillustrator","adobepremierepro","adobeaftereffects",
  "sketch","canva","blender",
]);
set("tools", [
  "vite","webpack","rollupdotjs","esbuild","turbo","swc","babel","pnpm","yarn","npm",
  "jest","vitest","mocha","cypress","playwright","selenium","puppeteer","storybook","testinglibrary",
  "postman","insomnia","swagger","notion","obsidian","slack","discord","jira","linear","trello",
  "visualstudiocode","neovim","vim","jetbrains","intellijidea","androidstudio","xcode",
  "pycharm","webstorm","phpstorm","goland","rubymine","rider","clion","datagrip",
  "sublimetext","atom","eclipseide","notepadplusplus","zedindustries","cursor","antigravity",
  "anaconda","pypi","poetry",
  "wordpress","shopify","strapi","sanity","contentful","ghost","unity","unrealengine",
  "godotengine","threedotjs","stripe",
  "paypal","mercadopago","twilio","sendgrid","resend","mailchimp","auth0","clerk","okta",
]);
set("ai", [
  "openai","anthropic","googlegemini","huggingface","tensorflow","pytorch","keras",
  "scikitlearn","pandas","numpy","jupyter","langchain","ollama",
]);

export function inferTechCategory(value: string): TechCategory {
  const t = resolveTech(value);
  if (t && CATEGORY_BY_SLUG[t.slug]) return CATEGORY_BY_SLUG[t.slug];
  return "tools";
}