/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TecnologiasRouteImport } from './routes/tecnologias'
import { Route as SobreMiRouteImport } from './routes/sobre-mi'
import { Route as ProyectosRouteImport } from './routes/proyectos'
import { Route as HabilidadesRouteImport } from './routes/habilidades'
import { Route as ExperienciaRouteImport } from './routes/experiencia'
import { Route as EducacionRouteImport } from './routes/educacion'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProyectosSlugRouteImport } from './routes/proyectos.$slug'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminTecnologiasRouteImport } from './routes/_authenticated/admin.tecnologias'
import { Route as AuthenticatedAdminProyectosRouteImport } from './routes/_authenticated/admin.proyectos'
import { Route as AuthenticatedAdminPerfilRouteImport } from './routes/_authenticated/admin.perfil'
import { Route as AuthenticatedAdminMenuRouteImport } from './routes/_authenticated/admin.menu'
import { Route as AuthenticatedAdminMensajesRouteImport } from './routes/_authenticated/admin.mensajes'
import { Route as AuthenticatedAdminHabilidadesRouteImport } from './routes/_authenticated/admin.habilidades'
import { Route as AuthenticatedAdminExperienciaRouteImport } from './routes/_authenticated/admin.experiencia'
import { Route as AuthenticatedAdminEducacionRouteImport } from './routes/_authenticated/admin.educacion'
import { Route as AuthenticatedAdminAnaliticasRouteImport } from './routes/_authenticated/admin.analiticas'

const TecnologiasRoute = TecnologiasRouteImport.update({
  id: '/tecnologias',
  path: '/tecnologias',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreMiRoute = SobreMiRouteImport.update({
  id: '/sobre-mi',
  path: '/sobre-mi',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosRoute = ProyectosRouteImport.update({
  id: '/proyectos',
  path: '/proyectos',
  getParentRoute: () => rootRouteImport,
} as any)
const HabilidadesRoute = HabilidadesRouteImport.update({
  id: '/habilidades',
  path: '/habilidades',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienciaRoute = ExperienciaRouteImport.update({
  id: '/experiencia',
  path: '/experiencia',
  getParentRoute: () => rootRouteImport,
} as any)
const EducacionRoute = EducacionRouteImport.update({
  id: '/educacion',
  path: '/educacion',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosSlugRoute = ProyectosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProyectosRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTecnologiasRoute =
  AuthenticatedAdminTecnologiasRouteImport.update({
    id: '/tecnologias',
    path: '/tecnologias',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProyectosRoute =
  AuthenticatedAdminProyectosRouteImport.update({
    id: '/proyectos',
    path: '/proyectos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPerfilRoute =
  AuthenticatedAdminPerfilRouteImport.update({
    id: '/perfil',
    path: '/perfil',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMenuRoute = AuthenticatedAdminMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminMensajesRoute =
  AuthenticatedAdminMensajesRouteImport.update({
    id: '/mensajes',
    path: '/mensajes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHabilidadesRoute =
  AuthenticatedAdminHabilidadesRouteImport.update({
    id: '/habilidades',
    path: '/habilidades',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminExperienciaRoute =
  AuthenticatedAdminExperienciaRouteImport.update({
    id: '/experiencia',
    path: '/experiencia',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEducacionRoute =
  AuthenticatedAdminEducacionRouteImport.update({
    id: '/educacion',
    path: '/educacion',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnaliticasRoute =
  AuthenticatedAdminAnaliticasRouteImport.update({
    id: '/analiticas',
    path: '/analiticas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contacto': typeof ContactoRoute
  '/educacion': typeof EducacionRoute
  '/experiencia': typeof ExperienciaRoute
  '/habilidades': typeof HabilidadesRoute
  '/proyectos': typeof ProyectosRouteWithChildren
  '/sobre-mi': typeof SobreMiRoute
  '/tecnologias': typeof TecnologiasRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/proyectos/$slug': typeof ProyectosSlugRoute
  '/admin/analiticas': typeof AuthenticatedAdminAnaliticasRoute
  '/admin/educacion': typeof AuthenticatedAdminEducacionRoute
  '/admin/experiencia': typeof AuthenticatedAdminExperienciaRoute
  '/admin/habilidades': typeof AuthenticatedAdminHabilidadesRoute
  '/admin/mensajes': typeof AuthenticatedAdminMensajesRoute
  '/admin/menu': typeof AuthenticatedAdminMenuRoute
  '/admin/perfil': typeof AuthenticatedAdminPerfilRoute
  '/admin/proyectos': typeof AuthenticatedAdminProyectosRoute
  '/admin/tecnologias': typeof AuthenticatedAdminTecnologiasRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contacto': typeof ContactoRoute
  '/educacion': typeof EducacionRoute
  '/experiencia': typeof ExperienciaRoute
  '/habilidades': typeof HabilidadesRoute
  '/proyectos': typeof ProyectosRouteWithChildren
  '/sobre-mi': typeof SobreMiRoute
  '/tecnologias': typeof TecnologiasRoute
  '/api/chat': typeof ApiChatRoute
  '/proyectos/$slug': typeof ProyectosSlugRoute
  '/admin/analiticas': typeof AuthenticatedAdminAnaliticasRoute
  '/admin/educacion': typeof AuthenticatedAdminEducacionRoute
  '/admin/experiencia': typeof AuthenticatedAdminExperienciaRoute
  '/admin/habilidades': typeof AuthenticatedAdminHabilidadesRoute
  '/admin/mensajes': typeof AuthenticatedAdminMensajesRoute
  '/admin/menu': typeof AuthenticatedAdminMenuRoute
  '/admin/perfil': typeof AuthenticatedAdminPerfilRoute
  '/admin/proyectos': typeof AuthenticatedAdminProyectosRoute
  '/admin/tecnologias': typeof AuthenticatedAdminTecnologiasRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contacto': typeof ContactoRoute
  '/educacion': typeof EducacionRoute
  '/experiencia': typeof ExperienciaRoute
  '/habilidades': typeof HabilidadesRoute
  '/proyectos': typeof ProyectosRouteWithChildren
  '/sobre-mi': typeof SobreMiRoute
  '/tecnologias': typeof TecnologiasRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/proyectos/$slug': typeof ProyectosSlugRoute
  '/_authenticated/admin/analiticas': typeof AuthenticatedAdminAnaliticasRoute
  '/_authenticated/admin/educacion': typeof AuthenticatedAdminEducacionRoute
  '/_authenticated/admin/experiencia': typeof AuthenticatedAdminExperienciaRoute
  '/_authenticated/admin/habilidades': typeof AuthenticatedAdminHabilidadesRoute
  '/_authenticated/admin/mensajes': typeof AuthenticatedAdminMensajesRoute
  '/_authenticated/admin/menu': typeof AuthenticatedAdminMenuRoute
  '/_authenticated/admin/perfil': typeof AuthenticatedAdminPerfilRoute
  '/_authenticated/admin/proyectos': typeof AuthenticatedAdminProyectosRoute
  '/_authenticated/admin/tecnologias': typeof AuthenticatedAdminTecnologiasRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contacto'
    | '/educacion'
    | '/experiencia'
    | '/habilidades'
    | '/proyectos'
    | '/sobre-mi'
    | '/tecnologias'
    | '/admin'
    | '/api/chat'
    | '/proyectos/$slug'
    | '/admin/analiticas'
    | '/admin/educacion'
    | '/admin/experiencia'
    | '/admin/habilidades'
    | '/admin/mensajes'
    | '/admin/menu'
    | '/admin/perfil'
    | '/admin/proyectos'
    | '/admin/tecnologias'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contacto'
    | '/educacion'
    | '/experiencia'
    | '/habilidades'
    | '/proyectos'
    | '/sobre-mi'
    | '/tecnologias'
    | '/api/chat'
    | '/proyectos/$slug'
    | '/admin/analiticas'
    | '/admin/educacion'
    | '/admin/experiencia'
    | '/admin/habilidades'
    | '/admin/mensajes'
    | '/admin/menu'
    | '/admin/perfil'
    | '/admin/proyectos'
    | '/admin/tecnologias'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contacto'
    | '/educacion'
    | '/experiencia'
    | '/habilidades'
    | '/proyectos'
    | '/sobre-mi'
    | '/tecnologias'
    | '/_authenticated/admin'
    | '/api/chat'
    | '/proyectos/$slug'
    | '/_authenticated/admin/analiticas'
    | '/_authenticated/admin/educacion'
    | '/_authenticated/admin/experiencia'
    | '/_authenticated/admin/habilidades'
    | '/_authenticated/admin/mensajes'
    | '/_authenticated/admin/menu'
    | '/_authenticated/admin/perfil'
    | '/_authenticated/admin/proyectos'
    | '/_authenticated/admin/tecnologias'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactoRoute: typeof ContactoRoute
  EducacionRoute: typeof EducacionRoute
  ExperienciaRoute: typeof ExperienciaRoute
  HabilidadesRoute: typeof HabilidadesRoute
  ProyectosRoute: typeof ProyectosRouteWithChildren
  SobreMiRoute: typeof SobreMiRoute
  TecnologiasRoute: typeof TecnologiasRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tecnologias': {
      id: '/tecnologias'
      path: '/tecnologias'
      fullPath: '/tecnologias'
      preLoaderRoute: typeof TecnologiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-mi': {
      id: '/sobre-mi'
      path: '/sobre-mi'
      fullPath: '/sobre-mi'
      preLoaderRoute: typeof SobreMiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos': {
      id: '/proyectos'
      path: '/proyectos'
      fullPath: '/proyectos'
      preLoaderRoute: typeof ProyectosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habilidades': {
      id: '/habilidades'
      path: '/habilidades'
      fullPath: '/habilidades'
      preLoaderRoute: typeof HabilidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiencia': {
      id: '/experiencia'
      path: '/experiencia'
      fullPath: '/experiencia'
      preLoaderRoute: typeof ExperienciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/educacion': {
      id: '/educacion'
      path: '/educacion'
      fullPath: '/educacion'
      preLoaderRoute: typeof EducacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos/$slug': {
      id: '/proyectos/$slug'
      path: '/$slug'
      fullPath: '/proyectos/$slug'
      preLoaderRoute: typeof ProyectosSlugRouteImport
      parentRoute: typeof ProyectosRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tecnologias': {
      id: '/_authenticated/admin/tecnologias'
      path: '/tecnologias'
      fullPath: '/admin/tecnologias'
      preLoaderRoute: typeof AuthenticatedAdminTecnologiasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/proyectos': {
      id: '/_authenticated/admin/proyectos'
      path: '/proyectos'
      fullPath: '/admin/proyectos'
      preLoaderRoute: typeof AuthenticatedAdminProyectosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/perfil': {
      id: '/_authenticated/admin/perfil'
      path: '/perfil'
      fullPath: '/admin/perfil'
      preLoaderRoute: typeof AuthenticatedAdminPerfilRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/menu': {
      id: '/_authenticated/admin/menu'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AuthenticatedAdminMenuRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/mensajes': {
      id: '/_authenticated/admin/mensajes'
      path: '/mensajes'
      fullPath: '/admin/mensajes'
      preLoaderRoute: typeof AuthenticatedAdminMensajesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/habilidades': {
      id: '/_authenticated/admin/habilidades'
      path: '/habilidades'
      fullPath: '/admin/habilidades'
      preLoaderRoute: typeof AuthenticatedAdminHabilidadesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/experiencia': {
      id: '/_authenticated/admin/experiencia'
      path: '/experiencia'
      fullPath: '/admin/experiencia'
      preLoaderRoute: typeof AuthenticatedAdminExperienciaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/educacion': {
      id: '/_authenticated/admin/educacion'
      path: '/educacion'
      fullPath: '/admin/educacion'
      preLoaderRoute: typeof AuthenticatedAdminEducacionRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analiticas': {
      id: '/_authenticated/admin/analiticas'
      path: '/analiticas'
      fullPath: '/admin/analiticas'
      preLoaderRoute: typeof AuthenticatedAdminAnaliticasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnaliticasRoute: typeof AuthenticatedAdminAnaliticasRoute
  AuthenticatedAdminEducacionRoute: typeof AuthenticatedAdminEducacionRoute
  AuthenticatedAdminExperienciaRoute: typeof AuthenticatedAdminExperienciaRoute
  AuthenticatedAdminHabilidadesRoute: typeof AuthenticatedAdminHabilidadesRoute
  AuthenticatedAdminMensajesRoute: typeof AuthenticatedAdminMensajesRoute
  AuthenticatedAdminMenuRoute: typeof AuthenticatedAdminMenuRoute
  AuthenticatedAdminPerfilRoute: typeof AuthenticatedAdminPerfilRoute
  AuthenticatedAdminProyectosRoute: typeof AuthenticatedAdminProyectosRoute
  AuthenticatedAdminTecnologiasRoute: typeof AuthenticatedAdminTecnologiasRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnaliticasRoute: AuthenticatedAdminAnaliticasRoute,
  AuthenticatedAdminEducacionRoute: AuthenticatedAdminEducacionRoute,
  AuthenticatedAdminExperienciaRoute: AuthenticatedAdminExperienciaRoute,
  AuthenticatedAdminHabilidadesRoute: AuthenticatedAdminHabilidadesRoute,
  AuthenticatedAdminMensajesRoute: AuthenticatedAdminMensajesRoute,
  AuthenticatedAdminMenuRoute: AuthenticatedAdminMenuRoute,
  AuthenticatedAdminPerfilRoute: AuthenticatedAdminPerfilRoute,
  AuthenticatedAdminProyectosRoute: AuthenticatedAdminProyectosRoute,
  AuthenticatedAdminTecnologiasRoute: AuthenticatedAdminTecnologiasRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ProyectosRouteChildren {
  ProyectosSlugRoute: typeof ProyectosSlugRoute
}

const ProyectosRouteChildren: ProyectosRouteChildren = {
  ProyectosSlugRoute: ProyectosSlugRoute,
}

const ProyectosRouteWithChildren = ProyectosRoute._addFileChildren(
  ProyectosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactoRoute: ContactoRoute,
  EducacionRoute: EducacionRoute,
  ExperienciaRoute: ExperienciaRoute,
  HabilidadesRoute: HabilidadesRoute,
  ProyectosRoute: ProyectosRouteWithChildren,
  SobreMiRoute: SobreMiRoute,
  TecnologiasRoute: TecnologiasRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
